#!/usr/bin/env bash
# Sets up local DNS so dev-mincirklen.dk (and its subdomains) resolve to
# this Mac's current LAN IP for the docker-compose.yml stack. Answering
# with the LAN IP (rather than 127.0.0.1) means the same hostname works
# both for local browsing and for a device tunneled in over the optional
# `vpn` service (./setup-local-vpn.sh) — a remote client can't do anything with a
# loopback answer. NOT executed automatically anywhere — run it yourself
# when you're ready:
#
#   ./setup-local-dns.sh
#
# Entirely self-contained to this repo: it only starts/uses this repo's own
# `dns` service (local-infra/dns/dnsmasq.conf, defined in docker-compose.yml) and
# never reads or modifies another project's DNS config. That does mean this
# stack's `dns` service and any other project's DNS container binding host
# port 53 can't run at the same time — stop the other one first if you hit
# a conflict.
#
# What it does, in order:
#   1. Detects this machine's current LAN IP and (re)generates
#      local-infra/dns/dnsmasq.conf (gitignored — machine/network-specific)
#      to answer dev-mincirklen.dk with it.
#   2. Starts (or recreates, if the answer changed) this repo's `dns`
#      container, bound to host port 53 on all interfaces.
#   3. Writes /etc/resolver/dev-mincirklen.dk (macOS's per-domain resolver
#      mechanism) so only queries for this domain go to the local dnsmasq —
#      every other domain keeps resolving normally. Requires sudo.
#   4. Flushes the macOS DNS cache and verifies resolution.
#
# Safe to re-run: every step checks current state before changing anything.
# Re-run any time your LAN IP changes (new Wi-Fi network, DHCP lease
# renewal) to fix resolution — local dev otherwise keeps pointing at the
# stale address.

set -euo pipefail

DOMAIN="dev-mincirklen.dk"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { printf '\033[1;34m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$1" >&2; }
die() {
  printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2
  exit 1
}

if [[ "$(uname -s)" != "Darwin" ]]; then
  die "This script only supports macOS (/etc/resolver is a macOS-specific mechanism). On Linux, point dev-mincirklen.dk at 127.0.0.1 via /etc/hosts or your systemd-resolved config instead."
fi

if [[ "$(id -u)" -eq 0 ]]; then
  die "Don't run this with sudo. The individual steps that need elevation (/etc/resolver, dscacheutil) already sudo themselves; running the whole script as root instead makes 'docker compose up' create host-mounted files owned by root, which then breaks bind mounts (like the caddy certs) for other containers running as your normal user. Just run: ./setup-local-dns.sh"
fi

command -v docker >/dev/null 2>&1 || die "docker is required (Docker Desktop or compatible) and wasn't found on PATH."
docker info >/dev/null 2>&1 || die "Docker daemon isn't running. Start Docker Desktop and try again."

# --- Step 1: detect LAN IP and (re)generate dnsmasq.conf ---

LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
[[ -n "$LAN_IP" ]] || die "Couldn't detect a LAN IP on en0/en1 — connect to Wi-Fi or Ethernet and re-run."

DNSMASQ_CONF="${REPO_ROOT}/local-infra/dns/dnsmasq.conf"
DNSMASQ_CONTENT="# Generated by setup-local-dns.sh — answers dev-mincirklen.dk with this
# machine's current LAN IP (${LAN_IP}), not committed (see .gitignore).
# Re-run setup-local-dns.sh if this machine's LAN IP changes.
address=/${DOMAIN}/${LAN_IP}

# Don't use the host's /etc/resolv.conf (avoids loops) — forward everything
# else to public resolvers instead. Required for the optional vpn service
# (./setup-local-vpn.sh): a tunneled client's DNS is this server for ALL queries,
# not just ${DOMAIN}, so it needs to actually resolve the rest of the
# internet too, not just NXDOMAIN/hang on every other domain.
no-resolv
server=1.1.1.1
server=8.8.8.8"

CONF_CHANGED=1
if [[ -f "$DNSMASQ_CONF" ]] && diff -q <(printf '%s\n' "$DNSMASQ_CONTENT") "$DNSMASQ_CONF" >/dev/null 2>&1; then
  CONF_CHANGED=0
fi

if [[ "$CONF_CHANGED" -eq 1 ]]; then
  log "Writing ${DNSMASQ_CONF} (LAN IP: ${LAN_IP})."
  printf '%s\n' "$DNSMASQ_CONTENT" > "$DNSMASQ_CONF"
fi

# --- Step 2: start (or recreate) this repo's own dns container ---

if docker ps --filter 'name=^mincirklen-dns$' --format '{{.Names}}' | grep -q mincirklen-dns; then
  if [[ "$CONF_CHANGED" -eq 1 ]]; then
    log "dnsmasq.conf changed — recreating mincirklen-dns to pick it up."
    docker compose -f "${REPO_ROOT}/docker-compose.yml" up -d --force-recreate dns
  else
    log "mincirklen-dns is already running with the current config."
  fi
else
  if lsof -nP -iUDP:53 >/dev/null 2>&1; then
    die "Host UDP port 53 is already in use by something else (check: lsof -nP -iUDP:53). Free it up — e.g. stop another project's DNS container — and re-run this script."
  fi
  log "Starting the dns service."
  docker compose -f "${REPO_ROOT}/docker-compose.yml" up -d dns
fi

# --- Step 3: macOS per-domain resolver (still points at the local dnsmasq
# on 127.0.0.1 — it's this machine's own resolver config, not the answer
# dnsmasq gives out) ---

RESOLVER_FILE="/etc/resolver/${DOMAIN}"
RESOLVER_CONTENT="nameserver 127.0.0.1"

if [[ -f "$RESOLVER_FILE" ]] && grep -qF "$RESOLVER_CONTENT" "$RESOLVER_FILE"; then
  log "${RESOLVER_FILE} already configured — leaving it as-is."
else
  log "Writing ${RESOLVER_FILE} (requires sudo)."
  sudo mkdir -p /etc/resolver
  printf '%s\n' "$RESOLVER_CONTENT" | sudo tee "$RESOLVER_FILE" >/dev/null
fi

# --- Step 4: flush cache and verify ---

log "Flushing macOS DNS cache."
sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder >/dev/null 2>&1 || true

sleep 1

log "Verifying resolution for ${DOMAIN} ..."
if [[ "$(dig +short "$DOMAIN" @127.0.0.1)" == "$LAN_IP" ]]; then
  log "Resolved correctly (-> ${LAN_IP})."
else
  warn "dig didn't return the expected answer — give the DNS container a few seconds and try: dig ${DOMAIN} @127.0.0.1"
fi

cat <<EOF

Done. Next steps:
  docker compose up -d --build
  open https://${DOMAIN}

Subdomains also route through Caddy:
  https://trpc.${DOMAIN}
  https://socket.${DOMAIN}
EOF
